wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      4: 3.7.3
      5: 0.10.32
      8:
      - 5
architecture:
  desc: null
  value: CNN
dataset_id:
  desc: null
  value: peds-0192
learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.2
